services:

  flask:
    image: prashantmhamunkar/flask-redis-app:latest
    container_name: flask-redis-app
    ports:
      - "80:5000"
    restart: --unless-stopped  

    environment: 
      REDIS_HOST: redis
    depends_on:
      - redis

  redis: 
    image: redis:7-alpine
    container_name: redis-flask  
    restart: --unless-stopped 
    volumes:
      - redis-data:/data
volumes: 
  redis-data: